# Generated by Django 4.2.27 on 2026-10-07 07:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bestelling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winkel", models.CharField(blank=True, default="", max_length=200)),
                ("ordernr", models.CharField(blank=True, default="", max_length=200)),
                ("besteld_op", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tracking_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("vervoerder", models.CharField(blank=True, default="", max_length=50)),
            ],
            options={
                "ordering": ["-besteld_op", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Gebruiker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=254, unique=True)),
                ("naam", models.CharField(blank=True, default="", max_length=200)),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Super-admin in TerraFlow (zoals laatst doorgegeven)",
                    ),
                ),
                ("mag_goedkeuren", models.BooleanField(default=False)),
                ("mag_bestellen", models.BooleanField(default=False)),
                ("laatst_gezien", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["naam", "email"],
            },
        ),
        migrations.CreateModel(
            name="Instelling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sleutel", models.CharField(max_length=100, unique=True)),
                ("waarde", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="MeldingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sleutel", models.CharField(max_length=200, unique=True)),
                (
                    "verstuurd_op",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winkel", models.CharField(max_length=200, unique=True)),
                ("url", models.URLField(blank=True, default="", max_length=1000)),
                ("notitie", models.CharField(blank=True, default="", max_length=300)),
                ("gevuld_op", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Regel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aanvrager_naam",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Naam uit de oude kooplijst, als er nog geen gebruiker aan gekoppeld is",
                        max_length=200,
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("link", models.CharField(blank=True, default="", max_length=2000)),
                (
                    "winkel",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=200
                    ),
                ),
                ("aantal", models.PositiveIntegerField(default=1)),
                ("per_verpakking", models.PositiveIntegerField(default=1)),
                (
                    "prijs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Totaalprijs in euro",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("project", models.CharField(blank=True, default="", max_length=200)),
                ("opmerking", models.CharField(blank=True, default="", max_length=500)),
                ("spoed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aangevraagd", "Wacht op akkoord"),
                            ("goedgekeurd", "Akkoord"),
                            ("besteld", "Besteld"),
                            ("ontvangen", "Ontvangen"),
                            ("afgewezen", "Afgewezen"),
                        ],
                        db_index=True,
                        default="aangevraagd",
                        max_length=20,
                    ),
                ),
                (
                    "aangevraagd_op",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("goedgekeurd_op", models.DateTimeField(blank=True, null=True)),
                ("ontvangen_op", models.DateTimeField(blank=True, null=True)),
                ("factuurnr", models.CharField(blank=True, default="", max_length=200)),
                (
                    "geimporteerd",
                    models.BooleanField(
                        default=False, help_text="Overgezet uit de oude Excel-kooplijst"
                    ),
                ),
                ("wagen_ok", models.BooleanField(blank=True, null=True)),
                (
                    "wagen_notitie",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "aanvrager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regels",
                        to="inkoop.gebruiker",
                    ),
                ),
                (
                    "bestelling",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regels",
                        to="inkoop.bestelling",
                    ),
                ),
                (
                    "goedgekeurd_door",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inkoop.gebruiker",
                    ),
                ),
            ],
            options={
                "ordering": ["-aangevraagd_op", "-id"],
            },
        ),
        migrations.AddField(
            model_name="bestelling",
            name="besteld_door",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="inkoop.gebruiker",
            ),
        ),
    ]
